def handle_error(error):
    print('Something went wrong...')
    print(error)
